### ISSUE TITLE
How to use it on docker

### ISSUE THREAD

**Issue by rajasekhar-gundala** [codelibs/fess-ds-sharepoint#3]
Hello, Thank you very much for the plugin. I installed FESS on the docker environment. Also installed the plugin under System-->Plugin

How to proceed after installation of the plugin.

![image](https://user-images.githubusercontent.com/633479/172113559-f79bd4e3-039c-4505-9ede-57f756753eb0.png)

**Comment by marevol** [comment]
You can mount the plugin directory with -v option of docker.

**Comment by rajasekhar-gundala** [comment]
> You can mount the plugin directory with -v option of docker.

@marevol, Thanks for the reply. I found below the steps to install the plugin. 

1. Download fess-ds-sharepoint-X.X.X.jar
2. Copy fess-ds-sharepoint-X.X.X.jar to $FESS_HOME/app/WEB-INF/lib or /usr/share/fess/app/WEB-INF/lib

As I mentioned previously I installed the plugin using FESS GUI. 

Do you want me to mount the volume like below in docker-compose?
```
volumes:
      - /mnt/plugins:$FESS_HOME/app/WEB-INF/lib or /usr/share/fess/app/WEB-INF/lib
```
